#!/usr/bin/env python3
"""
Example training command with EMA, SAM optimizer, and label smoothing
"""

# Basic training with new features
print("Example training commands:")
print()

print("1. Training with EMA, SAM, and Label Smoothing:")
print("python train.py \\")
print("    --data_dir /path/to/your/data \\")
print("    --epochs 100 \\")
print("    --batch_size 16 \\")
print("    --lr 5e-4 \\")
print("    --augment \\")
print("    --use_sam \\")
print("    --sam_rho 0.05 \\")
print("    --sam_adaptive \\")
print("    --use_ema \\")
print("    --ema_decay 0.9999 \\")
print("    --ema_warmup_steps 2000 \\")
print("    --label_smoothing 0.1 \\")
print("    --use_scheduler \\")
print("    --scheduler_type cosine \\")
print("    --save_dir ./checkpoints")
print()

print("2. Training with just EMA and label smoothing (no SAM):")
print("python train.py \\")
print("    --data_dir /path/to/your/data \\")
print("    --epochs 50 \\")
print("    --batch_size 32 \\")
print("    --lr 1e-3 \\")
print("    --use_ema \\")
print("    --label_smoothing 0.05 \\")
print("    --save_dir ./checkpoints_no_sam")
print()

print("3. Training with SAM only:")
print("python train.py \\")
print("    --data_dir /path/to/your/data \\")
print("    --epochs 75 \\")
print("    --batch_size 8 \\")
print("    --lr 3e-4 \\")
print("    --use_sam \\")
print("    --sam_rho 0.1 \\")
print("    --save_dir ./checkpoints_sam_only")
print()

print("Key changes in the updated training script:")
print("=" * 50)
print("✅ EMA (Exponential Moving Average):")
print("   - Maintains shadow weights for better inference")
print("   - Use --use_ema --ema_decay 0.9999 --ema_warmup_steps 2000")
print()
print("✅ SAM Optimizer (already supported, enhanced):")
print("   - Sharpness-Aware Minimization for better generalization")
print("   - Use --use_sam --sam_rho 0.05 --sam_adaptive")
print()
print("✅ Label Smoothing:")
print("   - Reduces overconfidence and improves generalization")
print("   - Use --label_smoothing 0.1 (recommended: 0.05-0.15)")
print()
print("✅ 64x512 Image Resizing:")
print("   - All images now resized to exactly 64x512 pixels")
print("   - No more chunking - simpler and faster processing")
print()
print("✅ Enhanced Checkpointing:")
print("   - EMA state saved/loaded with checkpoints")
print("   - Better resume functionality")
print()

print("Notes:")
print("- EMA typically improves validation performance by 1-3%")
print("- SAM can improve generalization but increases training time ~2x")
print("- Label smoothing helps prevent overfitting, especially with small datasets")
print("- The 64x512 resize makes training much faster and more predictable")
